# Variables associated with the discord bot
bot:
  # The token of the bot
  token: "replace-with-your-bot-token"
  # The command symbol of the bot
  symbol: "!"
# Variables associated with the database
db:
  # The path to the database
  path: "databases/pm.db"
